Gopkg.lock
Gopkg.toml
pkg/cmd/cmd_suite_test.go
pkg/cmd/dbshell.go
pkg/cmd/pyshell.go
pkg/cmd/shell.go
pkg/exec/exec.go
pkg/kubernetes/kubernetes.go

Adds `ridectl shell`, `ridectl pyshell`, and `ridectl dbshell` to prototype getting interactive access to various pieces of the system.

Shell commands

---

pkg/cmd/edit.go

The keys are all in west1 for now, just force it.

For now, just hardwire the region.

---

pkg/cmd/edit/edit_suite_test.go
pkg/cmd/edit/manifest.go
pkg/cmd/edit/manifest_test.go
pkg/cmd/edit/object.go
pkg/cmd/edit/object_test.go

Now with a few tests!
This is things like 
```
tls.key: |
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANasdfasdfasdfasdfasdfasdf
qwerqwerqwerqwerqwerqwerqwerqwerqwer
-----END PRIVATE KEY-----
```

Add support for block scalars.

---

.dockerignore
Dockerfile

Dockerfile for image builds.

---

.circleci/config.yml

Make sure .macos and .linux binaries no longer exist after zip

---

pkg/cmd/edit.go

Make the edit command work with vim and similar editors.

---

pkg/cmd/dbshell.go
pkg/cmd/doctor.go
pkg/cmd/lint.go
pkg/kubernetes/kubernetes.go

DBShell is working again using psql
Lint now fails when it finds duplicate Names
Added doctor test + fix for psql installation

Assorted improvements

---

pkg/cmd/dbshell.go
pkg/cmd/doctor.go
pkg/cmd/edit.go
pkg/cmd/loadflavor.go
pkg/cmd/password.go
pkg/cmd/pyshell.go
pkg/cmd/shell.go
pkg/kubernetes/kubernetes.go

Added automatic context handling for multiple cluster support

Multi-cluster support

---

README.md
pkg/cmd/redeploy.go
pkg/cmd/restart-migrations.go

Also, we need to provide user permission delete kind: `job ` https://github.com/Ridecell/kubernetes/pull/324

1st pass to support redeploy

---

pkg/cmd/dbshell.go
pkg/cmd/edit.go
pkg/cmd/loadflavor.go
pkg/cmd/password.go
pkg/cmd/periscope.go
pkg/cmd/pyshell.go
pkg/cmd/restart-migrations.go
pkg/cmd/restart.go
pkg/cmd/shell.go
pkg/kubernetes/kubernetes.go

We can access postgresdatabase connection information from the PostgresDatabase Object (which both summon instances and microservices have)

support microservices for dbshell, shell, pyshell cmds

---

pkg/cmd/lint.go

Make sure that each summon platform encrypted secret has FERNET_KEYS key-value.

DEVOPS-2561 Check fernet key

---

.circleci/config.yml
Gopkg.lock
pkg/cmd/edit/edit_suite_test.go
pkg/cmd/edit/manifest_test.go
pkg/cmd/edit/object.go
pkg/cmd/edit/object_test.go

Use Data key to encrypt and decrypt data.

DEVOPS-2727 Encryption changes

---

pkg/cmd/decrypt.go
pkg/cmd/edit/object.go
pkg/cmd/encrypt.go

Added encrypt/decrypt command for encryption of secret files/values files in microservice's kubernetes folder.
It will replace our existing owner key encryption flow.

DEVOPS-2801 Add encrypt/decrypt command

---

pkg/cmd/password.go

DEVOPS-2746 Initial password cmd

---

pkg/cmd/edit/manifest.go
pkg/cmd/lint.go

DevOps-2746 Ignore new operator objects while linting

---

pkg/cmd/lint.go

ignore namespace while linting

---

pkg/cmd/restart-migrations.go
pkg/cmd/status.go
pkg/kubernetes/kubernetes.go

use summonplatform object for summon-status

---

pkg/utils/utils.go

DEVOPS-2915 add check for VPN

---

pkg/kubernetes/kubernetes.go

make sure we return proper context

---

pkg/cmd/lint.go

don't lint if only namespace is found in manifest

---

pkg/cmd/edit/manifest.go
pkg/cmd/edit/object.go
pkg/cmd/lint.go

allow editing unregistered objects

---

pkg/cmd/pyshell.go
pkg/cmd/shell.go

fix pod exec issue in pyshell and shell

DEVOPS-3018 fix pod exec issue

---

pkg/cmd/restart-migrations.go
pkg/cmd/restart.go
pkg/kubernetes/kubernetes.go

Merge all restart commands (migration, pods rolling restart and postgresdump restart) under ridectl restart command.
Deprecate ridectl restart-migrations command.

DEVOPS-3076 Add PostgresDump restart support

---

go.mod
go.sum
pkg/cmd/root.go

Added web autoscaling support in SummonPlatform CRD
Update FAQs link

DEVOPS-2630 Update Summon-operator

---

pkg/cmd/dbshell.go
pkg/cmd/password.go
pkg/cmd/postgresdump.go
pkg/cmd/pyshell.go
pkg/cmd/restart.go
pkg/cmd/shell.go
pkg/cmd/status.go
pkg/utils/utils.go

- Turned repeated steps into function for ridectl cmds.
- Made minor adjustments to words and description

DEVOPS-3213 Checkinstance util func

---

Makefile

DEVOPS-3390Update teleport version in Makefile from 13.0.3 to 13.3.8

DEVOPS-3390Update teleport version in Makefile from 13.0.3 to 13.3.8
